### ISSUE TITLE
How does the "Cracked" Authentication works?

### ISSUE THREAD

**Issue by ABSanthosh** [dommilosz/minecraft-auth#5]
I have several questions:
1) How does it work? I went through the code and I can't seem to figure it out.
2) Does it work with the latest Minecraft launcher?
3) If it does, How to set this up?

Cheers!

**Comment by dommilosz** [comment]
Cracked authentication is simply setting username without logging in to mojang account. It doesn't allow to connect with online mode servers. As you see in readme.md cracked accounts are crated this way:
```
var minecraftAuth = require("minecraft-auth")
let account = new minecraftAuth.CrackedAccount("username");
```
It results with object:
![obraz](https://user-images.githubusercontent.com/54410730/146420271-11fb6aee-139d-423f-a931-f517e372492e.png)

Access token is undefined because no authentication was done. It just set the username and uuid

Answering 2 question. Original Minecraft Account doesn't allow you to play without buying the game.

**Comment by dommilosz** [comment]
Is that everything you need? Can close issue?

**Comment by ABSanthosh** [comment]
Yes, sorry. Ill close the issue. Thanks for replying!
